In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv(
    "../data/processed/credit_risk_feature_engineered.csv"
)

df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,TOTAL_PAYMENT,AVG_PAYMENT,CREDIT_UTILIZATION,PAYMENT_RATIO,AVG_DELAY,MAX_DELAY,NUM_DELAY_MONTHS,RECENT_DELAY_FLAG,BILL_GROWTH,PAYMENT_STD
0,1,20000,2,2,1,24,2,2,-1,-1,...,689,114.833333,0.385181,0.089422,-0.333333,2,2,1,3913,281.283072
1,2,120000,2,2,2,26,-1,2,0,0,...,5000,833.333333,0.142307,0.292774,0.500000,2,2,0,-579,752.772653
2,3,90000,2,2,2,34,0,0,0,0,...,11018,1836.333333,1.129465,0.108387,0.000000,0,0,0,13690,1569.815488
3,4,50000,2,2,1,37,0,0,0,0,...,8388,1398.000000,4.626587,0.036259,0.000000,0,0,0,17443,478.058155
4,5,50000,1,2,1,57,-1,0,-1,0,...,59049,9841.500000,2.186736,0.540049,-0.333333,0,0,0,-10514,13786.230736

In [3]:
print(df.columns.tolist())

['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default payment next month', 'AGE_GROUP', 'TOTAL_BILL', 'AVG_BILL', 'TOTAL_PAYMENT', 'AVG_PAYMENT', 'CREDIT_UTILIZATION', 'PAYMENT_RATIO', 'AVG_DELAY', 'MAX_DELAY', 'NUM_DELAY_MONTHS', 'RECENT_DELAY_FLAG', 'BILL_GROWTH', 'PAYMENT_STD']

In [4]:
target = "default payment next month"

feature_columns = [
    col
    for col in df.columns
    if col not in [
        target,
        "ID"
    ]
]

print("Number of Features:", len(feature_columns))
print(feature_columns)

Number of Features: 36
['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'AGE_GROUP', 'TOTAL_BILL', 'AVG_BILL', 'TOTAL_PAYMENT', 'AVG_PAYMENT', 'CREDIT_UTILIZATION', 'PAYMENT_RATIO', 'AVG_DELAY', 'MAX_DELAY', 'NUM_DELAY_MONTHS', 'RECENT_DELAY_FLAG', 'BILL_GROWTH', 'PAYMENT_STD']

In [5]:
X = df[feature_columns]

y = df[target]

print(X.shape)
print(y.shape)

(30000, 36)
(30000,)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Train Shape:", X_train.shape)
print("Test Shape:", X_test.shape)

Train Shape: (24000, 36)
Test Shape: (6000, 36)

In [ ]:
# Baseline model

lr_model = LogisticRegression(
    max_iter=5000,
    class_weight="balanced",
    random_state=42
)

lr_model.fit(X_train, y_train)

c:\Users\priti\anaconda3\envs\credit_risk_ml\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 5000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=5000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced', max_iter=5000, random_state=42)

In [ ]:
#Baseline model performance

y_pred_lr = lr_model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall   :", recall_score(y_test, y_pred_lr))
print("F1 Score :", f1_score(y_test, y_pred_lr))
print("ROC AUC  :", roc_auc_score(y_test, y_pred_lr))

Accuracy : 0.726
Precision: 0.41381185426862427
Recall   : 0.573474001507159
F1 Score : 0.48073278584965257
ROC AUC  : 0.6713935383097532

In [9]:
rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_split=20,
    min_samples_leaf=10,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=10, min_samples_split=20,
                       n_estimators=300, n_jobs=-1, random_state=42)

In [10]:
y_pred_rf = rf_model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall   :", recall_score(y_test, y_pred_rf))
print("F1 Score :", f1_score(y_test, y_pred_rf))
print("ROC AUC  :", roc_auc_score(y_test, y_pred_rf))

Accuracy : 0.818
Precision: 0.6607387140902873
Recall   : 0.36397889977392617
F1 Score : 0.46938775510204084
ROC AUC  : 0.6554540336661199

In [11]:
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

feature_importance.head(15)

               Feature  Importance
5                PAY_0    0.151835
30           AVG_DELAY    0.091202
33   RECENT_DELAY_FLAG    0.087863
31           MAX_DELAY    0.077687
32    NUM_DELAY_MONTHS    0.073967
6                PAY_2    0.045783
7                PAY_3    0.030366
28  CREDIT_UTILIZATION    0.025450
29       PAYMENT_RATIO    0.024421
27         AVG_PAYMENT    0.023373
26       TOTAL_PAYMENT    0.021389
0            LIMIT_BAL    0.021129
34         BILL_GROWTH    0.020443
9                PAY_5    0.020345
11           BILL_AMT1    0.019888

In [12]:
rf_model_balanced = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_split=20,
    min_samples_leaf=10,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_model_balanced.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_leaf=10, min_samples_split=20,
                       n_estimators=300, n_jobs=-1, random_state=42)

In [13]:
y_pred_rf_balanced = rf_model_balanced.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred_rf_balanced))
print("Precision:", precision_score(y_test, y_pred_rf_balanced))
print("Recall   :", recall_score(y_test, y_pred_rf_balanced))
print("F1 Score :", f1_score(y_test, y_pred_rf_balanced))
print("ROC AUC  :", roc_auc_score(y_test, y_pred_rf_balanced))

Accuracy : 0.782
Precision: 0.5061728395061729
Recall   : 0.5870384325546345
F1 Score : 0.5436147941381717
ROC AUC  : 0.7122010052779594

In [14]:
from sklearn.model_selection import RandomizedSearchCV

In [15]:
param_grid = {
    "n_estimators": [200, 300, 500, 700],
    "max_depth": [5, 8, 10, 12, 15, None],
    "min_samples_split": [2, 5, 10, 20],
    "min_samples_leaf": [1, 2, 5, 10],
    "max_features": ["sqrt", "log2"],
    "class_weight": [
        "balanced",
        "balanced_subsample"
    ]
}

In [16]:
random_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(
        random_state=42,
        n_jobs=-1
    ),
    param_distributions=param_grid,
    n_iter=25,
    scoring="roc_auc",
    cv=5,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits

RandomizedSearchCV(cv=5,
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   n_iter=25, n_jobs=-1,
                   param_distributions={'class_weight': ['balanced',
                                                         'balanced_subsample'],
                                        'max_depth': [5, 8, 10, 12, 15, None],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 20],
                                        'n_estimators': [200, 300, 500, 700]},
                   random_state=42, scoring='roc_auc', verbose=2)

In [17]:
print("Best Parameters:")
print(random_search.best_params_)

print("\nBest CV ROC-AUC:")
print(random_search.best_score_)

Best Parameters:
{'n_estimators': 700, 'min_samples_split': 20, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'max_depth': 10, 'class_weight': 'balanced_subsample'}

Best CV ROC-AUC:
0.786556821579711

In [18]:
best_rf = random_search.best_estimator_

y_pred_best_rf = best_rf.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred_best_rf))
print("Precision:", precision_score(y_test, y_pred_best_rf))
print("Recall   :", recall_score(y_test, y_pred_best_rf))
print("F1 Score :", f1_score(y_test, y_pred_best_rf))
print("ROC AUC  :", roc_auc_score(y_test, y_pred_best_rf))

Accuracy : 0.7813333333333333
Precision: 0.5048293625241468
Recall   : 0.5908063300678221
F1 Score : 0.5444444444444444
ROC AUC  : 0.7131219752200869

In [19]:
y_prob_best_rf = best_rf.predict_proba(X_test)[:, 1]

roc_auc_prob = roc_auc_score(
    y_test,
    y_prob_best_rf
)

print("Probability ROC-AUC:", roc_auc_prob)

Probability ROC-AUC: 0.7787562825840892

In [20]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test,
    y_pred_best_rf
)

print(cm)

[[3904  769]
 [ 543  784]]

In [21]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred_best_rf
    )
)

              precision    recall  f1-score   support

           0       0.88      0.84      0.86      4673
           1       0.50      0.59      0.54      1327

    accuracy                           0.78      6000
   macro avg       0.69      0.71      0.70      6000
weighted avg       0.80      0.78      0.79      6000

In [22]:
from xgboost import XGBClassifier

In [23]:
negative_class = (y_train == 0).sum()
positive_class = (y_train == 1).sum()

scale_pos_weight = (
    negative_class /
    positive_class
)

print(scale_pos_weight)

3.520625353173856

In [24]:
xgb_model = XGBClassifier(
    n_estimators=500,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric="logloss"
)

xgb_model.fit(
    X_train,
    y_train
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=500, n_jobs=None,
              num_parallel_tree=None, ...)

In [25]:
y_pred_xgb = xgb_model.predict(X_test)

y_prob_xgb = xgb_model.predict_proba(X_test)[:, 1]

print("Accuracy :", accuracy_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("Recall   :", recall_score(y_test, y_pred_xgb))
print("F1 Score :", f1_score(y_test, y_pred_xgb))
print(
    "ROC AUC  :",
    roc_auc_score(y_test, y_prob_xgb)
)

Accuracy : 0.7623333333333333
Precision: 0.4711033274956217
Recall   : 0.6081386586284853
F1 Score : 0.530921052631579
ROC AUC  : 0.7741104722071398

In [26]:
print(
    classification_report(
        y_test,
        y_pred_xgb
    )
)

              precision    recall  f1-score   support

           0       0.88      0.81      0.84      4673
           1       0.47      0.61      0.53      1327

    accuracy                           0.76      6000
   macro avg       0.67      0.71      0.69      6000
weighted avg       0.79      0.76      0.77      6000

In [27]:
from sklearn.model_selection import RandomizedSearchCV

In [28]:
xgb_param_grid = {
    "n_estimators": [300, 500, 700],
    "max_depth": [3, 4, 5, 6, 8],
    "learning_rate": [0.01, 0.03, 0.05, 0.1],
    "subsample": [0.7, 0.8, 0.9],
    "colsample_bytree": [0.7, 0.8, 0.9],
    "min_child_weight": [1, 3, 5],
    "gamma": [0, 0.1, 0.3]
}

In [29]:
xgb_search = RandomizedSearchCV(
    estimator=XGBClassifier(
        scale_pos_weight=scale_pos_weight,
        random_state=42,
        eval_metric="logloss"
    ),
    param_distributions=xgb_param_grid,
    n_iter=25,
    scoring="roc_auc",
    cv=5,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

xgb_search.fit(X_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits

RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric='logloss',
                                           feature_types=None,
                                           feature_weights=None, gamma=None,
                                           grow_policy=None,
                                           importance_type=None,
                                           interaction_cons...
                                           multi_strategy=None,
                                           n_estimators=None, n_jobs=None,
                                           num_parallel_tree=None, ...),
                   n_iter=25, n_jobs=-1,
                   param_distributions={'colsample_bytree': [0.7, 0.8, 0.9],
                                        'gamma': [0, 0.1, 0.3],
                                        'learning_rate': [0.01, 0.03, 0.05,
                                                          0.1],
                                        'max_depth': [3, 4, 5, 6, 8],
                                        'min_child_weight': [1, 3, 5],
                                        'n_estimators': [300, 500, 700],
                                        'subsample': [0.7, 0.8, 0.9]},
                   random_state=42, scoring='roc_auc', verbose=2)

In [30]:
print("Best Parameters:")
print(xgb_search.best_params_)

print("\nBest ROC-AUC:")
print(xgb_search.best_score_)

Best Parameters:
{'subsample': 0.8, 'n_estimators': 300, 'min_child_weight': 3, 'max_depth': 3, 'learning_rate': 0.03, 'gamma': 0, 'colsample_bytree': 0.9}

Best ROC-AUC:
0.7881662096201495

In [31]:
best_xgb = xgb_search.best_estimator_

y_prob_best_xgb = best_xgb.predict_proba(X_test)[:,1]

print(
    "Test ROC-AUC:",
    roc_auc_score(y_test, y_prob_best_xgb)
)

Test ROC-AUC: 0.7809305037791053

In [32]:
thresholds = [
    0.30,
    0.35,
    0.40,
    0.45,
    0.50,
    0.55,
    0.60
]

results = []

for threshold in thresholds:

    y_pred_threshold = (
        y_prob_best_xgb >= threshold
    ).astype(int)

    results.append({
        "Threshold": threshold,
        "Precision": precision_score(
            y_test,
            y_pred_threshold
        ),
        "Recall": recall_score(
            y_test,
            y_pred_threshold
        ),
        "F1": f1_score(
            y_test,
            y_pred_threshold
        )
    })

threshold_results = pd.DataFrame(results)

threshold_results

   Threshold  Precision    Recall        F1
0       0.30   0.301282  0.885456  0.449589
1       0.35   0.336603  0.827430  0.478536
2       0.40   0.370023  0.742276  0.493858
3       0.45   0.408573  0.675207  0.509091
4       0.50   0.455035  0.636775  0.530779
5       0.55   0.508704  0.594574  0.548297
6       0.60   0.542042  0.544084  0.543061

In [33]:
threshold_results.sort_values(
    by="F1",
    ascending=False
)

   Threshold  Precision    Recall        F1
5       0.55   0.508704  0.594574  0.548297
6       0.60   0.542042  0.544084  0.543061
4       0.50   0.455035  0.636775  0.530779
3       0.45   0.408573  0.675207  0.509091
2       0.40   0.370023  0.742276  0.493858
1       0.35   0.336603  0.827430  0.478536
0       0.30   0.301282  0.885456  0.449589

In [34]:
importance_df = pd.DataFrame({
    "Feature": feature_columns,
    "Importance": best_xgb.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

importance_df.head(20)

               Feature  Importance
31           MAX_DELAY    0.435483
32    NUM_DELAY_MONTHS    0.081811
5                PAY_0    0.075935
33   RECENT_DELAY_FLAG    0.053368
26       TOTAL_PAYMENT    0.027249
30           AVG_DELAY    0.026454
25            AVG_BILL    0.020691
24          TOTAL_BILL    0.018914
27         AVG_PAYMENT    0.017914
28  CREDIT_UTILIZATION    0.016406
0            LIMIT_BAL    0.015827
18            PAY_AMT2    0.012644
29       PAYMENT_RATIO    0.012401
22            PAY_AMT6    0.012218
19            PAY_AMT3    0.011924
6                PAY_2    0.011674
17            PAY_AMT1    0.010977
12           BILL_AMT2    0.010114
11           BILL_AMT1    0.009856
20            PAY_AMT4    0.009150

In [35]:
importance_df.tail(15)

        Feature  Importance
10        PAY_6    0.008068
1           SEX    0.008063
2     EDUCATION    0.007628
15    BILL_AMT5    0.007570
13    BILL_AMT3    0.007468
3      MARRIAGE    0.007196
35  PAYMENT_STD    0.007016
8         PAY_4    0.006607
14    BILL_AMT4    0.006517
4           AGE    0.006466
7         PAY_3    0.006463
21     PAY_AMT5    0.006272
16    BILL_AMT6    0.006109
9         PAY_5    0.004778
23    AGE_GROUP    0.004593

In [36]:
df["UTILIZATION_RECENT"] = (
    df["BILL_AMT1"] /
    (df["LIMIT_BAL"] + 1)
)

In [37]:
df["DELAY_TREND"] = (
    df["PAY_0"] -
    df["PAY_6"]
)

In [53]:
df["RECENT_BILL_RATIO"] = (
    df["BILL_AMT1"] /
    (np.abs(df["AVG_BILL"]) + 1)
)

In [54]:
df["RECENT_PAYMENT_RATIO"] = (
    df["PAY_AMT1"] /
    (df["AVG_PAYMENT"] + 1)
)

In [55]:
df["PAYMENT_TO_LIMIT_RATIO"] = (
    df["TOTAL_PAYMENT"] /
    (df["LIMIT_BAL"] + 1)
)

In [56]:
new_features = [
    "UTILIZATION_RECENT",
    "DELAY_TREND",
    "RECENT_BILL_RATIO",
    "RECENT_PAYMENT_RATIO",
    "PAYMENT_TO_LIMIT_RATIO"
]

df[new_features].head()

,UTILIZATION_RECENT,DELAY_TREND,RECENT_BILL_RATIO,RECENT_PAYMENT_RATIO,PAYMENT_TO_LIMIT_RATIO
0,0.195640,4,3.045136,0.000000,0.034448
1,0.022350,-3,0.941989,0.000000,0.041666
2,0.324874,0,1.725710,0.826197,0.122421
3,0.939781,0,1.218726,1.429593,0.167757
4,0.172337,-1,0.472834,0.203200,1.180956

In [57]:
target = "default payment next month"

feature_columns_v2 = [
    col
    for col in df.columns
    if col not in [
        target,
        "ID"
    ]
]

print("Number of Features:", len(feature_columns_v2))

Number of Features: 41

In [58]:
X_v2 = df[feature_columns_v2]

y_v2 = df[target]

In [59]:
X_train_v2, X_test_v2, y_train_v2, y_test_v2 = train_test_split(
    X_v2,
    y_v2,
    test_size=0.20,
    random_state=42,
    stratify=y_v2
)

In [60]:
new_features = [
    "UTILIZATION_RECENT",
    "DELAY_TREND",
    "RECENT_BILL_RATIO",
    "RECENT_PAYMENT_RATIO",
    "PAYMENT_TO_LIMIT_RATIO"
]

for col in new_features:
    print(f"\n{col}")

    print("NaN :", df[col].isna().sum())

    print(
        "Inf :",
        np.isinf(df[col]).sum()
    )

    print(
        "Min :",
        df[col].min()
    )

    print(
        "Max :",
        df[col].max()
    )

UTILIZATION_RECENT
NaN : 0
Inf : 0
Min : -0.6198895204419183
Max : 6.454977251137443

DELAY_TREND
NaN : 0
Inf : 0
Min : -7
Max : 7

RECENT_BILL_RATIO
NaN : 0
Inf : 0
Min : -1000.0
Max : 536.796812749004

RECENT_PAYMENT_RATIO
NaN : 0
Inf : 0
Min : 0.0
Max : 5.999570180046803

PAYMENT_TO_LIMIT_RATIO
NaN : 0
Inf : 0
Min : 0.0
Max : 14.566155423057213

In [61]:
df.replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

print(
    df.isnull().sum().sort_values(
        ascending=False
    ).head(20)
)

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
dtype: int64

In [62]:
print(
    "NaN:",
    df["RECENT_BILL_RATIO"].isna().sum()
)

print(
    "Inf:",
    np.isinf(
        df["RECENT_BILL_RATIO"]
    ).sum()
)

NaN: 0
Inf: 0

In [63]:
xgb_v2 = XGBClassifier(
    n_estimators=300,
    max_depth=3,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.9,
    min_child_weight=3,
    gamma=0,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric="logloss"
)

xgb_v2.fit(
    X_train_v2,
    y_train_v2
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.9, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=0,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=3, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [64]:
y_prob_v2 = xgb_v2.predict_proba(X_test_v2)[:, 1]

print(
    "ROC-AUC:",
    roc_auc_score(
        y_test_v2,
        y_prob_v2
    )
)

ROC-AUC: 0.7814046154285283

In [65]:
from lightgbm import LGBMClassifier

In [66]:
X = df[feature_columns]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [67]:
lgbm = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    num_leaves=31,
    max_depth=-1,
    subsample=0.8,
    colsample_bytree=0.8,
    class_weight="balanced",
    random_state=42
)

lgbm.fit(
    X_train,
    y_train
)

[LightGBM] [Info] Number of positive: 5309, number of negative: 18691
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001378 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5370
[LightGBM] [Info] Number of data points in the train set: 24000, number of used features: 36
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000

LGBMClassifier(class_weight='balanced', colsample_bytree=0.8,
               learning_rate=0.05, n_estimators=500, random_state=42,
               subsample=0.8)

In [68]:
y_prob_lgbm = lgbm.predict_proba(X_test)[:, 1]

print(
    "ROC-AUC:",
    roc_auc_score(
        y_test,
        y_prob_lgbm
    )
)

ROC-AUC: 0.7713638498898013

In [69]:
from catboost import CatBoostClassifier

In [70]:
cat_model = CatBoostClassifier(
    iterations=500,
    depth=6,
    learning_rate=0.05,
    loss_function="Logloss",
    eval_metric="AUC",
    auto_class_weights="Balanced",
    random_seed=42,
    verbose=0
)

cat_model.fit(
    X_train,
    y_train
)

CatBoostClassifier(auto_class_weights='Balanced', depth=6, eval_metric='AUC', iterations=500, learning_rate=0.05, loss_function='Logloss', random_seed=42, verbose=0)

In [71]:
y_prob_cat = cat_model.predict_proba(X_test)[:, 1]

print(
    "ROC-AUC:",
    roc_auc_score(
        y_test,
        y_prob_cat
    )
)

ROC-AUC: 0.7779267484600644

In [72]:
from imblearn.over_sampling import SMOTE

In [73]:
smote = SMOTE(
    sampling_strategy="auto",
    random_state=42
)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

print(X_train.shape)
print(X_train_smote.shape)

print(y_train.value_counts())
print(y_train_smote.value_counts())

(24000, 36)
(37382, 36)
default payment next month
0    18691
1     5309
Name: count, dtype: int64
default payment next month
0    18691
1    18691
Name: count, dtype: int64

In [74]:
xgb_smote = XGBClassifier(
    n_estimators=300,
    max_depth=3,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.9,
    min_child_weight=3,
    gamma=0,
    random_state=42,
    eval_metric="logloss"
)

xgb_smote.fit(
    X_train_smote,
    y_train_smote
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.9, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=0,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=3, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [75]:
y_prob_smote = xgb_smote.predict_proba(X_test)[:,1]

print(
    "ROC-AUC:",
    roc_auc_score(
        y_test,
        y_prob_smote
    )
)

ROC-AUC: 0.7562293674753925

In [76]:
from sklearn.ensemble import VotingClassifier

In [77]:
voting_model = VotingClassifier(
    estimators=[
        ("rf", best_rf),
        ("xgb", best_xgb)
    ],
    voting="soft"
)

voting_model.fit(
    X_train,
    y_train
)

VotingClassifier(estimators=[('rf',
                              RandomForestClassifier(class_weight='balanced_subsample',
                                                     max_depth=10,
                                                     min_samples_leaf=10,
                                                     min_samples_split=20,
                                                     n_estimators=700,
                                                     n_jobs=-1,
                                                     random_state=42)),
                             ('xgb',
                              XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=0.9, device=None,
                                            early_stopping_r...
                                            feature_weights=None, gamma=0,
                                            grow_policy=None,
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=0.03, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=3,
                                            max_leaves=None, min_child_weight=3,
                                            missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=300, n_jobs=None,
                                            num_parallel_tree=None, ...))],
                 voting='soft')

In [78]:
y_prob_vote = voting_model.predict_proba(X_test)[:,1]

print(
    "ROC-AUC:",
    roc_auc_score(
        y_test,
        y_prob_vote
    )
)

ROC-AUC: 0.7811557068125812

In [79]:
import os
import joblib
import json

os.makedirs(
    "../models/trained_models",
    exist_ok=True
)

In [80]:
joblib.dump(
    best_xgb,
    "../models/trained_models/credit_risk_xgb.pkl"
)

print("Model Saved")

Model Saved

In [81]:
joblib.dump(
    feature_columns,
    "../models/trained_models/feature_columns.pkl"
)

print("Feature Columns Saved")

Feature Columns Saved

In [82]:
metadata = {
    "model_name": "XGBoost",
    "roc_auc": 0.7809,
    "threshold": 0.55,
    "features": len(feature_columns)
}

with open(
    "../models/trained_models/model_metadata.json",
    "w"
) as f:
    json.dump(
        metadata,
        f,
        indent=4
    )

print("Metadata Saved")

Metadata Saved

In [83]:
import os

os.listdir(
    "../models/trained_models"
)

['credit_risk_xgb.pkl', 'feature_columns.pkl', 'model_metadata.json']